const ProductDetailsActionTypes = {
  PRODUCT_DETAILS_REQUEST: "PRODUCT_DETAILS_REQUEST",
  PRODUCT_DETAILS_SUCCESS: "PRODUCT_DETAILS_SUCCESS",
  PRODUCT_DETAILS_FAIL: "PRODUCT_DETAILS_FAIL",
};

export default ProductDetailsActionTypes;
